name: tokenizer_moqasem
description: Intelligent tokenization plugin with advanced Arabic support, fuzzy matching, phonetic analysis, and AI-powered text processing. Built with 95% AI assistance.
version: 1.0.0
homepage: https://github.com/Ahmed0Ghaith
repository: https://github.com/Ahmed0Ghaith/tokenizer_moqasem
issue_tracker: https://github.com/Ahmed0Ghaith/tokenizer_moqasem/issues
documentation: https://pub.dev/documentation/tokenizer_moqasem/latest/

topics:
  - tokenizer
  - nlp
  - arabic
  - text-processing
  - fuzzy-matching
  - ai

flutter:


environment:
  sdk: '>=3.9.0 <4.0.0'
dependencies:
  flutter_test:
    sdk: flutter
